from .auth import (
    UserRegisterRequest,
    UserLoginRequest,
    AuthResponse,
    UserResponse,
    TokenRefreshRequest,
    ForgotPasswordRequest,
    ForgotPasswordResponse,
    PasswordResetRequest,
    PasswordResetResponse,
    TokenLoginRequest,
    TokenVerifyRequest,
    GoogleOAuthRequest,
    GoogleOAuthResponse,
    GoogleUserInfo,
    SupabaseOAuthRequest,
    SupabaseOAuthResponse,
    OAuthErrorType,
    OAuthErrorResponse
)

from .points import (
    TransactionType,
    ServiceType,
    TransactionStatus,
    BillingType,
    PointTransaction,
    PointTransactionCreate,
    ConsumePointsRequest,
    ConsumePointsResponse,
    RechargePointsRequest,
    RechargePointsResponse,
    UserPointsBalance,
    PointPricingConfig,
    PointPricingConfigCreate,
    PointPricingConfigUpdate,
    CalculatePointsRequest,
    CalculatePointsResponse,
    PointTransactionQuery,
    PointTransactionHistoryResponse
)

from .voice import (
    TextToSpeechRequest,
    TextToSpeechResponse,
    VoiceInfo,
    VoicesResponse
)

__all__ = [
    # User schemas
    "UserRegisterRequest",
    "UserLoginRequest", 
    "AuthResponse",
    "UserResponse",
    "TokenRefreshRequest",
    "ForgotPasswordRequest",
    "ForgotPasswordResponse",
    "PasswordResetRequest",
    "PasswordResetResponse",
    "TokenLoginRequest",
    "TokenVerifyRequest",
    "GoogleOAuthRequest",
    "GoogleOAuthResponse",
    "GoogleUserInfo",
    "SupabaseOAuthRequest",
    "SupabaseOAuthResponse",
    "OAuthErrorType",
    "OAuthErrorResponse",
    # Material schemas
    "MaterialCreate",
    "MaterialUpdate",
    "MaterialResponse",
    "MaterialListResponse",
    "SegmentCreate",
    "SegmentUpdate", 
    "SegmentResponse",
    "MaterialProcessRequest",
    "MaterialAnalysisResponse",
    "NewWordsResponse",
    "GrammarPointsResponse",
    "MaterialSegmentationResponse",
    "MaterialSegmentationRequest",
    "ParsedTextResponse",
    "VocabularyResponse",
    "GrammarResponse",
    "GenerateExplanationRequest",
    "SegmentExplanationResponse",
    "SegmentExplanationCache",
    # Anki schemas
    "AnkiImportRequest",
    "AnkiImportResponse",
    "AnkiImportProgress",
    "AnkiDeckCreate",
    "AnkiDeckResponse",
    "AnkiDeckListResponse",
    "AnkiCardCreate",
    "AnkiCardResponse",
    "AnkiCardListResponse",
    "AnkiCardUpdate",
    "AnkiStudySessionCreate",
    "AnkiStudySessionResponse",
    "AnkiStudyProgressResponse",
    "AnkiStudyStatistics",
    # Task schemas
    "TaskCreate",
    "TaskUpdate", 
    "TaskResponse",
    "TaskListResponse",
    # Points schemas
    "PointsResponse",
    "ConsumePointsRequest",
    "ConsumePointsResponse",
    "RechargePointsRequest",
    "RechargePointsResponse",
    # Msg schemas
    "Msg",
    # Voice schemas
    "TextToSpeechRequest",
    "TextToSpeechResponse",
    "VoiceInfo",
    "VoicesResponse"
]
